travis:
  secure:
    BINSTAR_TOKEN: HtTpET1mA7v02qgs3lJq0bTvA42gK6wqY6iPk3bPhWay9fss8YEdF4o5QopJWbHJYqbXDo2n+tUmUk63YZrIex5kjTpkSZh5T5D6rK6wkTjLpArHsKRYyEBdCYJ2Y1RTxg9M0+ZMYuEYsYTIGYKfGZPnB/tDXZFQGBpsK2lUw00IZ4oMmptY1Vsbz5C4EKkPil66LtxblIbbYABIw+iJ0/8JuPxpz8kSHd1f2BZItWiXXhr0vGlu/gHZDr8wxxDfY2Jt+D8wfnoGBARV70fkd4vgze8d0FGNAk/GNggKDZ/F/nVQDHsElMwVDqvFq3nJwbNfLve4hEo7IKzmJCdQ2nHdv9IJvBZIvpZn0dmVzgGYU2cn2BfyOn81bwe/97vCmN/Wh7v1q3HeF/XoKM6xO9C5P0ABEXMFByAotnQBM8yoVX2hqQTcpBuk4c9VbIIrlN40A5zt9jknKMSjpwYxdu9FRQ+JfjgohJt7oRe2CDFifLSvw1HOIF7IFxOekaFUf1Vm/fkACRIs2sJQwV7uwwiVTDW6Hi2Dk74aGu4U6YF1ZmWiwl1PJdUufYubGrJdOGgSQGYe+rVSjVBxaq28aFTtZuhobMhmCnkFsod6phnB1n1XrBM5q7UR/eObIvn5WaYZ1smQReNryIKX2BtbyTCtx27/NivFaZt0PbLZVY0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
